// Package registry provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package registry

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ActorScopes.
const (
	Admin   ActorScopes = "admin"
	Manage  ActorScopes = "manage"
	Publish ActorScopes = "publish"
)

// Valid indicates whether the value is a known member of the ActorScopes enum.
func (e ActorScopes) Valid() bool {
	switch e {
	case Admin:
		return true
	case Manage:
		return true
	case Publish:
		return true
	default:
		return false
	}
}

// Defines values for ActorVia.
const (
	Session ActorVia = "session"
	Token   ActorVia = "token"
)

// Valid indicates whether the value is a known member of the ActorVia enum.
func (e ActorVia) Valid() bool {
	switch e {
	case Session:
		return true
	case Token:
		return true
	default:
		return false
	}
}

// Defines values for MaintainerRole.
const (
	MaintainerRoleMaintainer MaintainerRole = "maintainer"
	MaintainerRoleOwner      MaintainerRole = "owner"
)

// Valid indicates whether the value is a known member of the MaintainerRole enum.
func (e MaintainerRole) Valid() bool {
	switch e {
	case MaintainerRoleMaintainer:
		return true
	case MaintainerRoleOwner:
		return true
	default:
		return false
	}
}

// Actor Example: {"name":"chrille0313","scopes":["publish"],"token":{"expiresAt":"2026-12-01T00:00:00.000Z","name":"laptop"},"userId":"3f2c1e9a","via":"token"}
type Actor struct {
	// Name The user's display name
	Name   string        `json:"name"`
	Scopes []ActorScopes `json:"scopes"`

	// Token The publish token used; absent for a browser session
	Token *struct {
		// ExpiresAt Expiry, ISO 8601 UTC; null for a token that never expires
		ExpiresAt *time.Time `json:"expiresAt"`

		// Name The token's name on the account page
		Name *string `json:"name"`
	} `json:"token,omitempty"`
	UserId string `json:"userId"`

	// Via How the caller authenticated
	Via ActorVia `json:"via"`
}

// ActorScopes defines model for Actor.Scopes.
type ActorScopes string

// ActorVia How the caller authenticated
type ActorVia string

// DistTags Named pointers to versions; `latest` is always set
//
// Example: {"latest":"1.0.0"}
type DistTags struct {
	// Latest A semantic version
	//
	// Example: 1.0.0
	Latest               string            `json:"latest"`
	AdditionalProperties map[string]string `json:"-"`
}

// Maintainer Example: {"handle":"octocat","role":"owner","userId":"kq3vw7s5q1m9e8x2c4n6b0z1a7y5r3t9"}
type Maintainer struct {
	// Handle The account's handle, which is its GitHub login from when it signed up. Case-insensitive.
	//
	// Example: octocat
	Handle string `json:"handle"`

	// Role Every package has exactly one `owner`, the only one who can add or remove maintainers
	Role MaintainerRole `json:"role"`

	// UserId Stable account id
	//
	// Example: kq3vw7s5q1m9e8x2c4n6b0z1a7y5r3t9
	UserId string `json:"userId"`
}

// MaintainerRole Every package has exactly one `owner`, the only one who can add or remove maintainers
type MaintainerRole string

// Maintainers defines model for Maintainers.
type Maintainers struct {
	// Maintainers The owner first, then everyone else in the order they were added
	Maintainers []Maintainer `json:"maintainers"`
}

// Package defines model for Package.
type Package struct {
	// Author Example: chungindustries
	Author *string `json:"author,omitempty"`

	// CreatedAt When the package was first published, as an ISO 8601 UTC timestamp
	//
	// Example: 2026-01-15T12:00:00.000Z
	CreatedAt time.Time `json:"createdAt"`

	// DistTags Named pointers to versions; `latest` is always set
	//
	// Example: {"latest":"1.0.0"}
	DistTags DistTags `json:"dist-tags"`

	// Name Example: example
	Name string `json:"name"`

	// Versions Example: {"1.0.0":{"author":"chungindustries","createdAt":"2026-01-15T12:00:00.000Z","dependencies":{"cc-http":"^1.2.0"},"description":"Example utilities for CC:Tweaked computers","dist":{"bundle":{"sha256":"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08","size":4096,"url":"/packages/example/1.0.0/dist/bundle"},"tarball":{"integrity":"sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==","shasum":"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3","url":"/packages/example/1.0.0/dist/tarball"}},"name":"example","version":"1.0.0"}}
	Versions map[string]PackageVersion `json:"versions"`
}

// PackageSummary Example: {"author":"chungindustries","description":"Example utilities for CC:Tweaked computers","name":"example","publishedAt":"2026-01-15T12:00:00.000Z","version":"1.0.0","versionCount":3}
type PackageSummary struct {
	// Author Example: chungindustries
	Author *string `json:"author,omitempty"`

	// Description What the package does, in a sentence or two
	//
	// Example: Example utilities for CC:Tweaked computers
	Description *string `json:"description,omitempty"`

	// Name Example: example
	Name string `json:"name"`

	// PublishedAt When the latest version was published, as an ISO 8601 UTC timestamp
	//
	// Example: 2026-01-15T12:00:00.000Z
	PublishedAt time.Time `json:"publishedAt"`

	// Version The version `latest` points at
	//
	// Example: 1.0.0
	Version string `json:"version"`

	// VersionCount How many versions have been published
	//
	// Example: 3
	VersionCount int `json:"versionCount"`
}

// PackageVersion A published version: the manifest metadata plus its distribution artifacts and publish timestamp
type PackageVersion struct {
	// Author Example: chungindustries
	Author *string `json:"author,omitempty"`

	// CreatedAt When this version was published, as an ISO 8601 UTC timestamp
	//
	// Example: 2026-01-15T12:00:00.000Z
	CreatedAt time.Time `json:"createdAt"`

	// Dependencies The packages this one needs, each with the semver range it accepts
	//
	// Example: {"cc-http":"^1.2.0"}
	Dependencies *map[string]string `json:"dependencies,omitempty"`

	// Description What the package does, in a sentence or two
	//
	// Example: Example utilities for CC:Tweaked computers
	Description *string `json:"description,omitempty"`

	// Dist The downloadable artifacts for this version
	Dist struct {
		// Bundle The bundle built from the tarball: a length-prefixed manifest followed by the raw file bytes
		Bundle struct {
			// Sha256 SHA-256 of the bundle, in hex
			//
			// Example: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
			Sha256 string `json:"sha256"`

			// Size Bundle size in bytes, before any gzip on the wire
			//
			// Example: 4096
			Size int `json:"size"`

			// Url Where to download the bundle, which is what the in-game cpm client installs from
			//
			// Example: /packages/example/1.0.0/dist/bundle
			Url string `json:"url"`
		} `json:"bundle"`

		// Tarball The tarball as it was published: a gzipped tar of the package files
		Tarball struct {
			// Integrity Subresource Integrity (SRI) sha512 digest of the tarball
			//
			// Example: sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==
			Integrity string `json:"integrity"`

			// Shasum SHA-1 of the tarball, in hex
			//
			// Example: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
			Shasum string `json:"shasum"`

			// Url Where to download the tarball
			//
			// Example: /packages/example/1.0.0/dist/tarball
			Url string `json:"url"`
		} `json:"tarball"`
	} `json:"dist"`

	// Name Example: example
	Name string `json:"name"`

	// Startup A Lua file, relative to the package root, that the client runs when the computer boots
	//
	// Example: startup.lua
	Startup *string `json:"startup,omitempty"`

	// Version A semantic version
	//
	// Example: 1.0.0
	Version string `json:"version"`
}

// PackageVersionMetadata The package manifest: the `cpm.json` at the tarball root, which the registry treats as the metadata source of truth at publish
type PackageVersionMetadata struct {
	// Author Example: chungindustries
	Author *string `json:"author,omitempty"`

	// Dependencies The packages this one needs, each with the semver range it accepts
	//
	// Example: {"cc-http":"^1.2.0"}
	Dependencies *map[string]string `json:"dependencies,omitempty"`

	// Description What the package does, in a sentence or two
	//
	// Example: Example utilities for CC:Tweaked computers
	Description *string `json:"description,omitempty"`

	// Name Example: example
	Name string `json:"name"`

	// Startup A Lua file, relative to the package root, that the client runs when the computer boots
	//
	// Example: startup.lua
	Startup *string `json:"startup,omitempty"`

	// Version A semantic version
	//
	// Example: 1.0.0
	Version string `json:"version"`
}

// ResolveRequest defines model for ResolveRequest.
type ResolveRequest struct {
	// Dependencies Example: {"cc-http":"latest","example":"^1.2.0"}
	Dependencies map[string]string `json:"dependencies"`
}

// SearchResults defines model for SearchResults.
type SearchResults struct {
	// Results The requested page of matches
	Results []PackageSummary `json:"results"`

	// Total How many packages matched, across all pages
	//
	// Example: 1
	Total int `json:"total"`
}

// Getter for additional properties for DistTags. Returns the specified
// element and whether it was found
func (a DistTags) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DistTags
func (a *DistTags) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DistTags to handle AdditionalProperties
func (a *DistTags) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["latest"]; found {
		err = json.Unmarshal(raw, &a.Latest)
		if err != nil {
			return fmt.Errorf("error reading 'latest': %w", err)
		}
		delete(object, "latest")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DistTags to handle AdditionalProperties
func (a DistTags) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["latest"], err = json.Marshal(a.Latest)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'latest': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
