/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0582f20f57db6790a125749ada0c034d)
interface __BaseEnv_Env {
	REGISTRY: Fetcher /* cpm-registry */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
