/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 300fe06433747e17556508bdc3f4a096)
interface __BaseEnv_Env {
	REGISTRY: Fetcher /* cpm-registry */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
