/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ff6780f9f878927f6a3dc623a4631dc9)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
