-- Package ownership: who may publish a name. This is the authorization half of
-- auth (docs/cpm-registry-auth-design.md, section 8); authentication tables
-- live in 0003_auth.sql and are generated by Better Auth.
--
-- Exactly one row per package has role 'owner'; the partial unique index
-- enforces that. Authorization is a single indexed lookup on
-- (package_name, user_id), cheap enough to fold into the publish transaction
-- as a guarded INSERT (see D1RegistryStore.addVersion).

-- FK behaviors are deliberate: `user_id` is authorization and must die with
-- the account (CASCADE); `added_by` is provenance and merely anonymizes if the
-- adding account is ever deleted (SET NULL; also NULL for the system-claimed
-- owner row a first publish creates).
CREATE TABLE package_maintainers (
  package_name TEXT    NOT NULL,
  user_id      TEXT    NOT NULL,
  role         TEXT    NOT NULL CHECK (role IN ('owner', 'maintainer')),
  added_at     INTEGER NOT NULL,
  added_by     TEXT,
  PRIMARY KEY (package_name, user_id),
  FOREIGN KEY (package_name) REFERENCES packages (name) ON DELETE CASCADE,
  FOREIGN KEY (user_id)      REFERENCES "user" (id)     ON DELETE CASCADE,
  FOREIGN KEY (added_by)     REFERENCES "user" (id)     ON DELETE SET NULL
);

CREATE UNIQUE INDEX package_maintainers_single_owner
  ON package_maintainers (package_name) WHERE role = 'owner';

CREATE INDEX package_maintainers_by_user ON package_maintainers (user_id);

-- Names nobody may claim: infrastructure names, and names freed by a removal
-- (kept as tombstones so a removed package name can never be re-registered by
-- someone else). `cpm` itself is deliberately NOT reserved: it is a real
-- published package, claimed by its owner through first authenticated publish.
CREATE TABLE reserved_names (
  name       TEXT    NOT NULL PRIMARY KEY,
  reason     TEXT,
  created_at INTEGER NOT NULL
);

INSERT INTO reserved_names (name, reason, created_at) VALUES
  ('chung',    'infrastructure name', strftime('%s', 'now') * 1000),
  ('registry', 'infrastructure name', strftime('%s', 'now') * 1000);

-- Append-only record of every state change that is not itself a version
-- insert. Written from phase 4 onward (maintainer changes, transfers); the
-- table exists now so those migrations stay additive. Deliberately no foreign
-- keys: an audit log must never be reachable by a cascade, and its rows may
-- reference users and packages that no longer exist.
CREATE TABLE audit_events (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_user_id TEXT,
  action        TEXT    NOT NULL,
  package_name  TEXT,
  detail        TEXT,
  created_at    INTEGER NOT NULL
);

CREATE INDEX audit_events_by_package ON audit_events (package_name, created_at);
