-- better-auth 1.7 added `account.issuer` (with a uniqueness guarantee per
-- issuer + provider account) to the schema; 0003_auth.sql was generated by the
-- 1.6-era CLI while the installed runtime resolved to 1.7.2 through the ^1.6
-- range, so sign-ins failed with "no such column: account.issuer". Additive
-- catch-up because 0003 is already applied. The DEFAULT '' exists only to
-- satisfy ALTER TABLE on a NOT NULL column; the table was empty when this was
-- written and 1.7 writes an explicit issuer on every insert.
--
-- The runtime deps are pinned exactly from now on; regenerate future auth
-- schema changes with the CLI version matching package.json (see
-- auth-schema.config.ts) and diff against the applied migrations.

ALTER TABLE account ADD COLUMN issuer TEXT NOT NULL DEFAULT '';

CREATE UNIQUE INDEX "account_issuer_accountId_uidx" ON account ("issuer", "accountId");
